### ISSUE TITLE
Delete relationship strategy cannot implemented? (cascade, restrict, etc) 

### ISSUE THREAD

**Issue by ruchin96** [taufikarifuddin/sugarorm-example#1]
how to delete constraint data ?

**Comment by taufikarifuddin** [comment]
@ruchin96 bisa pake static method deleteAll()
misal ada soal yang memiliki bidang dan ingin menghapus soal yang berkaitan dengan bidang tertentu
deleteAll(Soal.class,"bidang=?",bidang.getId());
